<?php
	session_start();
	session_destroy();
	unset($_SESSION['userName']);
	unset($_SESSION['userMail']);
	unset($_SESSION['userAddress']);
	unset($_SESSION['userAvatar']);
	unset($_SESSION['userContact']);
	unset($_SESSION['userBirth']);
	unset($_SESSION['userGender']);
	unset($_SESSION['userBranch']);
	header("location:../../staff.html?AfcNPvBRjkR2Gm9YkHh6bcjGGwo5yp-ksa-rfaKaX9d249OdXuqO_V7N3f6whj47mh3Ki-jIoVo9EoscBILPPCdur50eOgQhnS08lOEtgiCAFw&smuh=62062&lh=Ac_3Aa17kZYZrw22");
?>	